-- Oracle-compatible schema for AI MCQ Quiz Generator
-- Run these in SQL Developer (XE). Adjust user/schema as needed.

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) UNIQUE NOT NULL,
  password_hash VARCHAR2(255) NOT NULL,
  subject VARCHAR2(100),
  institution VARCHAR2(255)
);

CREATE TABLE quizzes (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  subject VARCHAR2(100),
  difficulty VARCHAR2(20),
  num_questions NUMBER,
  created_at DATE DEFAULT SYSDATE,
  questions_clob CLOB
);

CREATE TABLE questions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id NUMBER NOT NULL,
  q_text CLOB,
  opt_a VARCHAR2(1000),
  opt_b VARCHAR2(1000),
  opt_c VARCHAR2(1000),
  opt_d VARCHAR2(1000),
  order_index NUMBER
);

CREATE TABLE answer_keys (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id NUMBER NOT NULL,
  encrypted_blob BLOB
);

-- Indexes & foreign keys (optional)
CREATE INDEX idx_quizzes_user ON quizzes(user_id);
CREATE INDEX idx_questions_quiz ON questions(quiz_id);
CREATE INDEX idx_answers_quiz ON answer_keys(quiz_id);

-- Note: add FK constraints after you verify owners and users.
